#!/bin/zsh
function bookmarks() {
	typeset -A bookmarks
	while read k v; do bookmarks[$k]="$v"; done < ~/.bookmarks
	target=$(printf "%s\n" ${(k)bookmarks} | fzf)
	cd ${~bookmarks[$target]}
}

function zle-bookmarks() {
	bookmarks
	zle reset-prompt
}
zle -N  zle-bookmarks
