#!/bin/zsh

exit(){builtin exit;}
zle -N q exit

bindkey -M vicmd ! edit-command-line-tmux

#unicode input
autoload -U insert-unicode-char
bindkey $'\26u'  insert-unicode-char
bindkey "\e."  insert-last-word

bindkey "^[[2~" yank                    # Insert
bindkey "^[[3~" delete-char             # Del
bindkey "^[[5~" history-beginning-search-backward  # PageUp
bindkey "^[[6~" history-beginning-search-forward  # PageDown
bindkey "^[e"   expand-cmd-path         # C-e for expanding path of typed command.
bindkey "^[[A"  up-line-or-search       # Up arrow for back-history-search.
bindkey "^[[B"  down-line-or-search     # Down arrow for fwd-history-search.
bindkey " "     magic-space             # Do history expansion on space.
bindkey $'\177'    backward-delete-char   #backspace
bindkey $'\10'    backward-delete-word   #C-backspace
case "$TERM" in
	*xterm*|(dt|k)term)
		bindkey "\e[H"  beginning-of-line       # Pos1
		bindkey "\e[F"  end-of-line             # End
	;;
	rxvt*|Eterm)
		bindkey "\e[7~" beginning-of-line       # Pos1
		bindkey "\e[8~" end-of-line             # End
	;;
	linux|screen*)
		bindkey "\e[1~" beginning-of-line       # Pos1
		bindkey "\e[4~" end-of-line             # End
	;;
esac
bindkey "\eOA" up-line-or-history
bindkey "\eOB" down-line-or-history
bindkey "\e[1;5D" vi-backward-blank-word
bindkey "\e[1;5C" vi-forward-blank-word
#bindkey . rationalise-dot

bindkey $'\20' push-line-or-edit
